
package es.informatica.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolaWSImpl", targetNamespace = "http://ws.informatica.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolaWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decirHola", targetNamespace = "http://ws.informatica.es/", className = "es.informatica.cliente.DecirHola")
    @ResponseWrapper(localName = "decirHolaResponse", targetNamespace = "http://ws.informatica.es/", className = "es.informatica.cliente.DecirHolaResponse")
    @Action(input = "http://ws.informatica.es/HolaWSImpl/decirHolaRequest", output = "http://ws.informatica.es/HolaWSImpl/decirHolaResponse")
    public String decirHola(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
